apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: app
spec:
  containers:
    - image: trianwar/hit-counter
      name: app
      ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
      app: app
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
    - image: redis:6-alpine
      name: redis
      ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-lb
spec:
  type: ClusterIP
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
      app: redis

